In [1]:
# Importation des bibliothèques nécessaires
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.multioutput import MultiOutputClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
import re
import nltk
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

In [2]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/0869778/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [3]:
stemmer = PorterStemmer()

In [4]:
#nlp = pd.read_csv('../perf_logger/tests_data/nlp_research_paper.csv', delimiter=',')
nlp = pd.read_csv('../perf_logger/tests_data/bbc-text.csv', delimiter=',')

In [5]:
nlp.shape

(2225, 2)

In [6]:
def preprocess(text):
    text = text.lower() # Conversion en minuscules
    text = re.sub('[^\w\s]', '', text) # Suppression de la ponctuation
    tokens = word_tokenize(text) #Tokenization
    stemmed_tokens = [stemmer.stem(token) for token in tokens] #Stemming permet de réduire les mots à leur racine, cela peut aider à améliorer les performances de la classification en réduisant la complexité
    return ' '.join(stemmed_tokens) # Retourne le texte nettoyé et stemmé

In [7]:
nlp['processed_text'] = nlp['text'].apply(preprocess)

In [8]:

nlp.shape

(2225, 3)

In [9]:
nlp.columns

Index(['label', 'text', 'processed_text'], dtype='object')

In [10]:
nlp.head()

,label,text,processed_text
0,tech,tv future in the hands of viewers with home th...,tv futur in the hand of viewer with home theat...
1,business,worldcom boss left books alone former worldc...,worldcom boss left book alon former worldcom b...
2,sport,tigers wary of farrell gamble leicester say ...,tiger wari of farrel gambl leicest say they wi...
3,sport,yeading face newcastle in fa cup premiership s...,yead face newcastl in fa cup premiership side ...
4,entertainment,ocean s twelve raids box office ocean s twelve...,ocean s twelv raid box offic ocean s twelv the...

In [11]:
nlp.iloc[:,2:4]

                                         processed_text
0     tv futur in the hand of viewer with home theat...
1     worldcom boss left book alon former worldcom b...
2     tiger wari of farrel gambl leicest say they wi...
3     yead face newcastl in fa cup premiership side ...
4     ocean s twelv raid box offic ocean s twelv the...
...                                                 ...
2220  car pull down us retail figur us retail sale f...
2221  kilroy unveil immigr polici exchatshow host ro...
2222  rem announc new glasgow concert us band rem ha...
2223  how polit squabbl snowbal it s becom commonpla...
2224  souness delight at euro progress boss graem so...

[2225 rows x 1 columns]

In [12]:
nlp.iloc[:, 5:10]

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[2225 rows x 0 columns]

In [13]:
labels = nlp['text']
mlb = MultiLabelBinarizer()
labels_binarized = mlb.fit_transform(labels.values)

In [14]:
labels_binarized

array([[1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 1, 0, 1],
       [1, 0, 0, ..., 1, 0, 0],
       ...,
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 1, 0, 0]])

In [15]:
X_train, X_test, y_train, y_test = train_test_split(nlp['text'], labels_binarized, test_size = 0.2, random_state= 42)
print('X_train shape:', X_train.shape)
print('X_test shape :', X_test.shape)
print('y_train shape:', y_train.shape)
print('y_test shape:', y_test.shape)

X_train shape: (1780,)
X_test shape : (445,)
y_train shape: (1780, 57)
y_test shape: (445, 57)

In [16]:
# CounVecrorizer est une technique de prétraitement de texte courament utilisée dans les tâches de traitement du langage naturel NLP pour convertir une collection de documents textuels en une representation numerique
# CounVectorize procède à la tokenization des données textuelles et au comptage des occurences de chaque token, il crée ensuite une matrice dont les lgnes reprtesentent les documents et les colonnes les mots-clés. Les valeurs cellules indiquent la fréquence de chaque mo clé dans chaque document. Cette matrice est connue sous le nom de matrice document terme


vectorizer = CountVectorizer(stop_words = 'english')
X_train_counts = vectorizer.fit_transform(X_train)
X_test_counts = vectorizer.transform(X_test)

In [17]:
X_train_counts.shape

(1780, 26327)

In [18]:
clf = MultiOutputClassifier(MultinomialNB())
clf.fit(X_train_counts, y_train)
y_pred = clf.predict(X_test_counts)

In [19]:
y_pred

array([[1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 1, 0, 1],
       [1, 0, 0, ..., 1, 1, 0],
       ...,
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 1, 0, 1],
       [1, 0, 0, ..., 1, 0, 1]])

In [20]:
from sklearn.metrics import *
print('accuracy score:', accuracy_score(y_test, y_pred))
print('precision score:', precision_score(y_test, y_pred, average = 'samples'))
print('recall score:', recall_score(y_test, y_pred, average= 'samples'))
print('f1 score :', f1_score(y_test, y_pred, average = 'samples'))

accuracy score: 0.02696629213483146
precision score: 0.9223925732082057
recall score: 0.9369814894454216
f1 score : 0.9270987983942793

In [21]:
pip install gensim

/stockage/robin/automl/.venv/bin/python: No module named pip
Note: you may need to restart the kernel to use updated packages.

In [22]:
import pandas as pd
pd.options.mode.chained_assignment = None
import numpy as np
import re
import nltk
import gensim
from gensim.models import word2vec
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
%matplotlib inline